#put into config/appliation.yml

development:
  s3_bucket: "BUCKET-NAME-DEV"

production:
  s3_bucket: "BUCKET-NAME-PRO"

s3_region:  "AWS_REGION"
s3_access_key_id: "XXXX"
s3_secret_access_key: "XXXX"
